on:
  poll:
    url: ${{ secrets.API }}
    shouldIncludeBody: true
    config:
      limit: 5
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Info
        env:
          DOWNLOAD_URL: ${{ on.poll.outputs.assets[0].browser_download_url }}
          TAG_NAME: ${{ on.poll.outputs.tag_name }}
        run: |
          echo "DOWNLOAD_URL: $DOWNLOAD_URL"
          echo "TAG_NAME: $TAG_NAME"
      - name: Download zip
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.ARIA2RPC }}
          method: POST
          body: |
            {
              "jsonrpc":"2.0", 
              "method":"aria2.addUri",
              "id":"qwer",
              "params":["token:${{ secrets.TOKEN }}",[
              "${{ on.poll.outputs.assets[0].browser_download_url }}"
              ],{"dir":"${{ secrets.DOWNLOAD_DIR }}/${{ on.poll.outputs.tag_name }}"}]
            }
      - name: Download Source Code
        uses: actionsflow/axios@main
        with:
          url: ${{ secrets.ARIA2RPC }}
          method: POST
          body: |
            {
              "jsonrpc":"2.0", 
              "method":"aria2.addUri",
              "id":"qwer",
              "params":["token:${{ secrets.TOKEN }}",[
              "${{ on.poll.outputs.zipball_url }}"
              ],{"dir":"${{ secrets.DOWNLOAD_DIR }}/${{ on.poll.outputs.tag_name }}"}]
            }
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Released: ${{ on.poll.outputs.name }}
